/* File: tmscore_wrapmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Jun 20 23:17:53 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *tmscore_wrap_error;
static PyObject *tmscore_wrap_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = tmscore_wrap_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(tmscore,TMSCORE)(int*,float*,float*,float*,int*,int*,float*,float*,float*,int*,float*,float*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** tmscore **********************************/
static char doc_f2py_rout_tmscore_wrap_tmscore[] = "\
tm,rcomm,lcomm = tmscore(l1,x1,y1,z1,n1,l2,x2,y2,z2,n2)\n\nWrapper for ``tmscore``.\
\n\nParameters\n----------\n"
"l1 : input int\n"
"x1 : input rank-1 array('f') with bounds (3000)\n"
"y1 : input rank-1 array('f') with bounds (3000)\n"
"z1 : input rank-1 array('f') with bounds (3000)\n"
"n1 : input rank-1 array('i') with bounds (3000)\n"
"l2 : input int\n"
"x2 : input rank-1 array('f') with bounds (3000)\n"
"y2 : input rank-1 array('f') with bounds (3000)\n"
"z2 : input rank-1 array('f') with bounds (3000)\n"
"n2 : input rank-1 array('i') with bounds (3000)\n"
"\nReturns\n-------\n"
"tm : float\n"
"rcomm : float\n"
"lcomm : int";
/* extern void F_FUNC(tmscore,TMSCORE)(int*,float*,float*,float*,int*,int*,float*,float*,float*,int*,float*,float*,int*); */
static PyObject *f2py_rout_tmscore_wrap_tmscore(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,int*,int*,float*,float*,float*,int*,float*,float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int l1 = 0;
  PyObject *l1_capi = Py_None;
  float *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  float *y1 = NULL;
  npy_intp y1_Dims[1] = {-1};
  const int y1_Rank = 1;
  PyArrayObject *capi_y1_tmp = NULL;
  int capi_y1_intent = 0;
  PyObject *y1_capi = Py_None;
  float *z1 = NULL;
  npy_intp z1_Dims[1] = {-1};
  const int z1_Rank = 1;
  PyArrayObject *capi_z1_tmp = NULL;
  int capi_z1_intent = 0;
  PyObject *z1_capi = Py_None;
  int *n1 = NULL;
  npy_intp n1_Dims[1] = {-1};
  const int n1_Rank = 1;
  PyArrayObject *capi_n1_tmp = NULL;
  int capi_n1_intent = 0;
  PyObject *n1_capi = Py_None;
  int l2 = 0;
  PyObject *l2_capi = Py_None;
  float *x2 = NULL;
  npy_intp x2_Dims[1] = {-1};
  const int x2_Rank = 1;
  PyArrayObject *capi_x2_tmp = NULL;
  int capi_x2_intent = 0;
  PyObject *x2_capi = Py_None;
  float *y2 = NULL;
  npy_intp y2_Dims[1] = {-1};
  const int y2_Rank = 1;
  PyArrayObject *capi_y2_tmp = NULL;
  int capi_y2_intent = 0;
  PyObject *y2_capi = Py_None;
  float *z2 = NULL;
  npy_intp z2_Dims[1] = {-1};
  const int z2_Rank = 1;
  PyArrayObject *capi_z2_tmp = NULL;
  int capi_z2_intent = 0;
  PyObject *z2_capi = Py_None;
  int *n2 = NULL;
  npy_intp n2_Dims[1] = {-1};
  const int n2_Rank = 1;
  PyArrayObject *capi_n2_tmp = NULL;
  int capi_n2_intent = 0;
  PyObject *n2_capi = Py_None;
  float tm = 0;
  float rcomm = 0;
  int lcomm = 0;
  static char *capi_kwlist[] = {"l1","x1","y1","z1","n1","l2","x2","y2","z2","n2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO:tmscore_wrap.tmscore",\
    capi_kwlist,&l1_capi,&x1_capi,&y1_capi,&z1_capi,&n1_capi,&l2_capi,&x2_capi,&y2_capi,&z2_capi,&n2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lcomm */
  /* Processing variable x1 */
  x1_Dims[0]=3000;
  capi_x1_intent |= F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(NPY_FLOAT,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 2nd argument `x1' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    x1 = (float *)(PyArray_DATA(capi_x1_tmp));

  /* Processing variable y1 */
  y1_Dims[0]=3000;
  capi_y1_intent |= F2PY_INTENT_IN;
  capi_y1_tmp = array_from_pyobj(NPY_FLOAT,y1_Dims,y1_Rank,capi_y1_intent,y1_capi);
  if (capi_y1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 3rd argument `y1' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    y1 = (float *)(PyArray_DATA(capi_y1_tmp));

  /* Processing variable tm */
  /* Processing variable l2 */
    f2py_success = int_from_pyobj(&l2,l2_capi,"tmscore_wrap.tmscore() 6th argument (l2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable l1 */
    f2py_success = int_from_pyobj(&l1,l1_capi,"tmscore_wrap.tmscore() 1st argument (l1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable x2 */
  x2_Dims[0]=3000;
  capi_x2_intent |= F2PY_INTENT_IN;
  capi_x2_tmp = array_from_pyobj(NPY_FLOAT,x2_Dims,x2_Rank,capi_x2_intent,x2_capi);
  if (capi_x2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 7th argument `x2' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    x2 = (float *)(PyArray_DATA(capi_x2_tmp));

  /* Processing variable n1 */
  n1_Dims[0]=3000;
  capi_n1_intent |= F2PY_INTENT_IN;
  capi_n1_tmp = array_from_pyobj(NPY_INT,n1_Dims,n1_Rank,capi_n1_intent,n1_capi);
  if (capi_n1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 5th argument `n1' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    n1 = (int *)(PyArray_DATA(capi_n1_tmp));

  /* Processing variable n2 */
  n2_Dims[0]=3000;
  capi_n2_intent |= F2PY_INTENT_IN;
  capi_n2_tmp = array_from_pyobj(NPY_INT,n2_Dims,n2_Rank,capi_n2_intent,n2_capi);
  if (capi_n2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 10th argument `n2' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    n2 = (int *)(PyArray_DATA(capi_n2_tmp));

  /* Processing variable y2 */
  y2_Dims[0]=3000;
  capi_y2_intent |= F2PY_INTENT_IN;
  capi_y2_tmp = array_from_pyobj(NPY_FLOAT,y2_Dims,y2_Rank,capi_y2_intent,y2_capi);
  if (capi_y2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 8th argument `y2' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    y2 = (float *)(PyArray_DATA(capi_y2_tmp));

  /* Processing variable z1 */
  z1_Dims[0]=3000;
  capi_z1_intent |= F2PY_INTENT_IN;
  capi_z1_tmp = array_from_pyobj(NPY_FLOAT,z1_Dims,z1_Rank,capi_z1_intent,z1_capi);
  if (capi_z1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 4th argument `z1' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    z1 = (float *)(PyArray_DATA(capi_z1_tmp));

  /* Processing variable z2 */
  z2_Dims[0]=3000;
  capi_z2_intent |= F2PY_INTENT_IN;
  capi_z2_tmp = array_from_pyobj(NPY_FLOAT,z2_Dims,z2_Rank,capi_z2_intent,z2_capi);
  if (capi_z2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tmscore_wrap_error,"failed in converting 9th argument `z2' of tmscore_wrap.tmscore to C/Fortran array" );
  } else {
    z2 = (float *)(PyArray_DATA(capi_z2_tmp));

  /* Processing variable rcomm */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&l1,x1,y1,z1,n1,&l2,x2,y2,z2,n2,&tm,&rcomm,&lcomm);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("ffi",tm,rcomm,lcomm);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable rcomm */
  if((PyObject *)capi_z2_tmp!=z2_capi) {
    Py_XDECREF(capi_z2_tmp); }
  }  /*if (capi_z2_tmp == NULL) ... else of z2*/
  /* End of cleaning variable z2 */
  if((PyObject *)capi_z1_tmp!=z1_capi) {
    Py_XDECREF(capi_z1_tmp); }
  }  /*if (capi_z1_tmp == NULL) ... else of z1*/
  /* End of cleaning variable z1 */
  if((PyObject *)capi_y2_tmp!=y2_capi) {
    Py_XDECREF(capi_y2_tmp); }
  }  /*if (capi_y2_tmp == NULL) ... else of y2*/
  /* End of cleaning variable y2 */
  if((PyObject *)capi_n2_tmp!=n2_capi) {
    Py_XDECREF(capi_n2_tmp); }
  }  /*if (capi_n2_tmp == NULL) ... else of n2*/
  /* End of cleaning variable n2 */
  if((PyObject *)capi_n1_tmp!=n1_capi) {
    Py_XDECREF(capi_n1_tmp); }
  }  /*if (capi_n1_tmp == NULL) ... else of n1*/
  /* End of cleaning variable n1 */
  if((PyObject *)capi_x2_tmp!=x2_capi) {
    Py_XDECREF(capi_x2_tmp); }
  }  /*if (capi_x2_tmp == NULL) ... else of x2*/
  /* End of cleaning variable x2 */
  } /*if (f2py_success) of l1*/
  /* End of cleaning variable l1 */
  } /*if (f2py_success) of l2*/
  /* End of cleaning variable l2 */
  /* End of cleaning variable tm */
  if((PyObject *)capi_y1_tmp!=y1_capi) {
    Py_XDECREF(capi_y1_tmp); }
  }  /*if (capi_y1_tmp == NULL) ... else of y1*/
  /* End of cleaning variable y1 */
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  /* End of cleaning variable lcomm */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of tmscore *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"tmscore",-1,{{-1}},0,(char *)F_FUNC(tmscore,TMSCORE),(f2py_init_func)f2py_rout_tmscore_wrap_tmscore,doc_f2py_rout_tmscore_wrap_tmscore},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "tmscore_wrap",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_tmscore_wrap(void) {
#else
#define RETVAL
PyMODINIT_FUNC inittmscore_wrap(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = tmscore_wrap_module = PyModule_Create(&moduledef);
#else
  m = tmscore_wrap_module = Py_InitModule("tmscore_wrap", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module tmscore_wrap (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'tmscore_wrap' is auto-generated with f2py (version:2).\nFunctions:\n"
"  tm,rcomm,lcomm = tmscore(l1,x1,y1,z1,n1,l2,x2,y2,z2,n2)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  tmscore_wrap_error = PyErr_NewException ("tmscore_wrap.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"tmscore_wrap");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
