/* File: distance_fortranmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Jun 20 15:58:38 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *distance_fortran_error;
static PyObject *distance_fortran_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(distance_fortran_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = distance_fortran_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(calc_distance,CALC_DISTANCE)(int*,int*,int*,int*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* calc_distance *******************************/
static char doc_f2py_rout_distance_fortran_calc_distance[] = "\
distance = calc_distance(c1,c2,[c1_size,n1,c2_size,n2])\n\nWrapper for ``calc_distance``.\
\n\nParameters\n----------\n"
"c1 : input rank-2 array('d') with bounds (c1_size,n1)\n"
"c2 : input rank-2 array('d') with bounds (c2_size,n2)\n"
"\nOther Parameters\n----------------\n"
"c1_size : input int, optional\n    Default: shape(c1,0)\n"
"n1 : input int, optional\n    Default: shape(c1,1)\n"
"c2_size : input int, optional\n    Default: shape(c2,0)\n"
"n2 : input int, optional\n    Default: shape(c2,1)\n"
"\nReturns\n-------\n"
"distance : rank-2 array('d') with bounds (c1_size,c2_size)";
/* extern void F_FUNC_US(calc_distance,CALC_DISTANCE)(int*,int*,int*,int*,double*,double*,double*); */
static PyObject *f2py_rout_distance_fortran_calc_distance(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int c1_size = 0;
  PyObject *c1_size_capi = Py_None;
  int n1 = 0;
  PyObject *n1_capi = Py_None;
  int c2_size = 0;
  PyObject *c2_size_capi = Py_None;
  int n2 = 0;
  PyObject *n2_capi = Py_None;
  double *c1 = NULL;
  npy_intp c1_Dims[2] = {-1, -1};
  const int c1_Rank = 2;
  PyArrayObject *capi_c1_tmp = NULL;
  int capi_c1_intent = 0;
  PyObject *c1_capi = Py_None;
  double *c2 = NULL;
  npy_intp c2_Dims[2] = {-1, -1};
  const int c2_Rank = 2;
  PyArrayObject *capi_c2_tmp = NULL;
  int capi_c2_intent = 0;
  PyObject *c2_capi = Py_None;
  double *distance = NULL;
  npy_intp distance_Dims[2] = {-1, -1};
  const int distance_Rank = 2;
  PyArrayObject *capi_distance_tmp = NULL;
  int capi_distance_intent = 0;
  static char *capi_kwlist[] = {"c1","c2","c1_size","n1","c2_size","n2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OOOO:distance_fortran.calc_distance",\
    capi_kwlist,&c1_capi,&c2_capi,&c1_size_capi,&n1_capi,&c2_size_capi,&n2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable c2 */
  ;
  capi_c2_intent |= F2PY_INTENT_IN;
  capi_c2_tmp = array_from_pyobj(NPY_DOUBLE,c2_Dims,c2_Rank,capi_c2_intent,c2_capi);
  if (capi_c2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(distance_fortran_error,"failed in converting 2nd argument `c2' of distance_fortran.calc_distance to C/Fortran array" );
  } else {
    c2 = (double *)(PyArray_DATA(capi_c2_tmp));

  /* Processing variable c1 */
  ;
  capi_c1_intent |= F2PY_INTENT_IN;
  capi_c1_tmp = array_from_pyobj(NPY_DOUBLE,c1_Dims,c1_Rank,capi_c1_intent,c1_capi);
  if (capi_c1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(distance_fortran_error,"failed in converting 1st argument `c1' of distance_fortran.calc_distance to C/Fortran array" );
  } else {
    c1 = (double *)(PyArray_DATA(capi_c1_tmp));

  /* Processing variable c1_size */
  if (c1_size_capi == Py_None) c1_size = shape(c1,0); else
    f2py_success = int_from_pyobj(&c1_size,c1_size_capi,"distance_fortran.calc_distance() 1st keyword (c1_size) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(c1,0)==c1_size,"shape(c1,0)==c1_size","1st keyword c1_size","calc_distance:c1_size=%d",c1_size) {
  /* Processing variable c2_size */
  if (c2_size_capi == Py_None) c2_size = shape(c2,0); else
    f2py_success = int_from_pyobj(&c2_size,c2_size_capi,"distance_fortran.calc_distance() 3rd keyword (c2_size) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(c2,0)==c2_size,"shape(c2,0)==c2_size","3rd keyword c2_size","calc_distance:c2_size=%d",c2_size) {
  /* Processing variable n1 */
  if (n1_capi == Py_None) n1 = shape(c1,1); else
    f2py_success = int_from_pyobj(&n1,n1_capi,"distance_fortran.calc_distance() 2nd keyword (n1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(c1,1)==n1,"shape(c1,1)==n1","2nd keyword n1","calc_distance:n1=%d",n1) {
  /* Processing variable n2 */
  if (n2_capi == Py_None) n2 = shape(c2,1); else
    f2py_success = int_from_pyobj(&n2,n2_capi,"distance_fortran.calc_distance() 4th keyword (n2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(c2,1)==n2,"shape(c2,1)==n2","4th keyword n2","calc_distance:n2=%d",n2) {
  /* Processing variable distance */
  distance_Dims[0]=c1_size,distance_Dims[1]=c2_size;
  capi_distance_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_distance_tmp = array_from_pyobj(NPY_DOUBLE,distance_Dims,distance_Rank,capi_distance_intent,Py_None);
  if (capi_distance_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(distance_fortran_error,"failed in converting hidden `distance' of distance_fortran.calc_distance to C/Fortran array" );
  } else {
    distance = (double *)(PyArray_DATA(capi_distance_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&c1_size,&n1,&c2_size,&n2,c1,c2,distance);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_distance_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_distance_tmp == NULL) ... else of distance*/
  /* End of cleaning variable distance */
  } /*CHECKSCALAR(shape(c2,1)==n2)*/
  } /*if (f2py_success) of n2*/
  /* End of cleaning variable n2 */
  } /*CHECKSCALAR(shape(c1,1)==n1)*/
  } /*if (f2py_success) of n1*/
  /* End of cleaning variable n1 */
  } /*CHECKSCALAR(shape(c2,0)==c2_size)*/
  } /*if (f2py_success) of c2_size*/
  /* End of cleaning variable c2_size */
  } /*CHECKSCALAR(shape(c1,0)==c1_size)*/
  } /*if (f2py_success) of c1_size*/
  /* End of cleaning variable c1_size */
  if((PyObject *)capi_c1_tmp!=c1_capi) {
    Py_XDECREF(capi_c1_tmp); }
  }  /*if (capi_c1_tmp == NULL) ... else of c1*/
  /* End of cleaning variable c1 */
  if((PyObject *)capi_c2_tmp!=c2_capi) {
    Py_XDECREF(capi_c2_tmp); }
  }  /*if (capi_c2_tmp == NULL) ... else of c2*/
  /* End of cleaning variable c2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of calc_distance ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"calc_distance",-1,{{-1}},0,(char *)F_FUNC_US(calc_distance,CALC_DISTANCE),(f2py_init_func)f2py_rout_distance_fortran_calc_distance,doc_f2py_rout_distance_fortran_calc_distance},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "distance_fortran",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_distance_fortran(void) {
#else
#define RETVAL
PyMODINIT_FUNC initdistance_fortran(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = distance_fortran_module = PyModule_Create(&moduledef);
#else
  m = distance_fortran_module = Py_InitModule("distance_fortran", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module distance_fortran (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'distance_fortran' is auto-generated with f2py (version:2).\nFunctions:\n"
"  distance = calc_distance(c1,c2,c1_size=shape(c1,0),n1=shape(c1,1),c2_size=shape(c2,0),n2=shape(c2,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  distance_fortran_error = PyErr_NewException ("distance_fortran.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"distance_fortran");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
